#!/bin/bash

# A hook called in the chroot phase of the image building process.

readonly WORK_DIR='/work'

readonly PACKAGES_DIR="${WORK_DIR}/packages"
readonly REMOVE_PACKAGES_PATH="${PACKAGES_DIR}/remove.txt"

function remove_packages() {
    echo "Removing Packages"

    cat "${REMOVE_PACKAGES_PATH}" | xargs apt remove --purge --yes

    apt autoremove --yes
    apt autoclean --yes
}

# See: https://salsa.debian.org/live-team/live-build/-/blob/master/examples/hooks/stripped.hook.chroot?ref_type=heads
function remove_files() {
    rm -rf /usr/include/*
    rm -rf /usr/share/doc/*
    rm -rf /usr/share/locale/*
    rm -rf /usr/share/man/*
    rm -rf /usr/share/i18n/*
    rm -rf /usr/share/info/*
    rm -rf /usr/share/lintian/*
    rm -rf /usr/share/linda/*
    rm -rf /usr/share/zoneinfo/*
    rm -rf /var/cache/man/*
}

function main() {
    trap exit SIGINT
    set -e

    # Remove Unwanted Packages
    remove_packages

    # Remove Work Directory
    echo "Removing Work Directory"
    rm -rf "${WORK_DIR}"

    return 0
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
