#!/bin/bash

# A hook called when the image is booting, before a user can assume control.

readonly BASE_DIR='/opt/qfcc'
readonly DATA_DIR="${BASE_DIR}/data"
readonly SHORTCUTS_DIR="${DATA_DIR}/shortcuts"

function setup_users() {
    echo "Setting Up Users"

    echo 'qfcc:qfcc' | chpasswd
}

function setup_desktop() {
    echo "Setting up Desktop"

    chown -R qfcc:qfcc /home/qfcc/Desktop
    echo 'XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share:/home/qfcc/Desktop' >> /etc/environment
}

function main() {
    trap exit SIGINT
    set -e

    # Setup Users
    setup_users

    # Setup Desktop
    setup_desktop

    return 0
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
